apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    path: config/crd/experimental
    targetRevision: v1.1.0 # Using experimental as required by recent NGF versions or features
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default # CRDs are cluster-wide, but app needs a dest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # CRDs are huge
